# inherit_from: .rubocop_todo.yml

# Common configuration.
AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'doc/**/*'
    - 'public/tmp/**/*'
    - 'public/uploads/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true

Style/NegatedIf:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/DotPosition:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/Not:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/AndOr:
  Enabled: false

# Removing BlockDelimiters Cop for RSpec
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15
